packages:
  - docs
  - packages/*

autoInstallPeers: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - dtrace-provider
  - esbuild
  - sharp
  - simple-git-hooks
  - spawn-sync

patchedDependencies:
  chrome-launcher@1.2.0: patches/chrome-launcher@1.2.0.patch
  markdown-it-footnote: patches/markdown-it-footnote.patch
  web-ext-run@0.2.4: patches/web-ext-run@0.2.4.patch

peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - search-insights
    - svelte
